"""create_innovatex_schema

Revision ID: 4731ae582abc
Revises: 
Create Date: 2026-09-21 16:11:52.884297
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4731ae582abc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('name', sa.String(length=240), server_default='', nullable=False),
    sa.Column('kind', sa.Enum('School', 'College', name='institution_kind', native_enum=False, create_constraint=True), server_default='College', nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=120), server_default='', nullable=False),
    sa.Column('region', sa.String(length=120), server_default='', nullable=False),
    sa.Column('country_code', sa.String(length=2), server_default='IN', nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_institutions_name_required')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutions')),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_institutions_name', 'institutions', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), server_default='', nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('role', sa.Enum('student', 'faculty', 'industry', 'mentor', 'admin', name='user_role', native_enum=False, create_constraint=True), server_default='student', nullable=False),
    sa.Column('virtual_id', sa.String(length=40), nullable=True),
    sa.Column('virtual_id_year', sa.Integer(), nullable=True),
    sa.Column('virtual_id_sequence', sa.BigInteger(), nullable=True),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('registered_by_id', sa.Uuid(), nullable=True),
    sa.Column('organization', sa.String(length=240), server_default='', nullable=False),
    sa.Column('department', sa.String(length=160), server_default='', nullable=False),
    sa.Column('bio', sa.Text(), server_default='', nullable=False),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('invited', 'active', 'suspended', 'deleted', name='user_status', native_enum=False, create_constraint=True), server_default='invited', nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(virtual_id IS NULL AND virtual_id_year IS NULL AND virtual_id_sequence IS NULL) OR (virtual_id IS NOT NULL AND virtual_id_year BETWEEN 1000 AND 9999 AND virtual_id_sequence > 0 AND virtual_id = (CASE role WHEN 'student' THEN 'STU' WHEN 'faculty' THEN 'FAC' WHEN 'industry' THEN 'IND' WHEN 'mentor' THEN 'MEN' ELSE 'ADM' END) || '-' || virtual_id_year::text || '-' || lpad(virtual_id_sequence::text, greatest(4, length(virtual_id_sequence::text)), '0'))", name=op.f('ck_users_virtual_identity')),
    sa.CheckConstraint("email = lower(trim(email)) AND email LIKE '%%_@_%%._%%'", name=op.f('ck_users_email_normalized')),
    sa.CheckConstraint("status <> 'active' OR (virtual_id IS NOT NULL AND password_hash IS NOT NULL)", name=op.f('ck_users_active_identity')),
    sa.CheckConstraint('length(trim(display_name)) > 0', name=op.f('ck_users_display_name_required')),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_users_institution_id_institutions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], name=op.f('fk_users_registered_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('role', 'virtual_id_sequence', name=op.f('uq_users_role')),
    sa.UniqueConstraint('virtual_id')
    )
    op.create_index(op.f('ix_users_institution_id'), 'users', ['institution_id'], unique=False)
    op.create_index(op.f('ix_users_registered_by_id'), 'users', ['registered_by_id'], unique=False)
    op.create_index('uq_users_email_normalized', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('institution_change_requests',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('from_institution_id', sa.Uuid(), nullable=False),
    sa.Column('to_institution_id', sa.Uuid(), nullable=False),
    sa.Column('faculty_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', name='institution_change_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('responded_by_id', sa.Uuid(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_note', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'pending' AND responded_at IS NULL AND responded_by_id IS NULL) OR (status <> 'pending' AND responded_at IS NOT NULL AND responded_by_id IS NOT NULL AND responded_by_id = faculty_id)", name=op.f('ck_institution_change_requests_change_response')),
    sa.CheckConstraint('from_institution_id <> to_institution_id', name=op.f('ck_institution_change_requests_different_institutions')),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_institution_change_requests_faculty_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_institution_id'], ['institutions.id'], name=op.f('fk_institution_change_requests_from_institution_id_institutions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responded_by_id'], ['users.id'], name=op.f('fk_institution_change_requests_responded_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_institution_change_requests_student_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_institution_id'], ['institutions.id'], name=op.f('fk_institution_change_requests_to_institution_id_institutions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institution_change_requests'))
    )
    op.create_index(op.f('ix_institution_change_requests_faculty_id'), 'institution_change_requests', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_institution_change_requests_from_institution_id'), 'institution_change_requests', ['from_institution_id'], unique=False)
    op.create_index(op.f('ix_institution_change_requests_responded_by_id'), 'institution_change_requests', ['responded_by_id'], unique=False)
    op.create_index(op.f('ix_institution_change_requests_student_id'), 'institution_change_requests', ['student_id'], unique=False)
    op.create_index(op.f('ix_institution_change_requests_to_institution_id'), 'institution_change_requests', ['to_institution_id'], unique=False)
    op.create_index('uq_student_pending_change', 'institution_change_requests', ['student_id'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('portfolio_shares',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug IS NOT NULL AND slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f('ck_portfolio_shares_share_slug')),
    sa.CheckConstraint('NOT enabled OR revoked_at IS NULL', name=op.f('ck_portfolio_shares_revoked_is_private')),
    sa.CheckConstraint('view_count >= 0', name=op.f('ck_portfolio_shares_view_count')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_portfolio_shares_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_shares')),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_portfolio_shares_owner_id'), 'portfolio_shares', ['owner_id'], unique=False)
    op.create_index('uq_portfolio_current_owner', 'portfolio_shares', ['owner_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('problems',
    sa.Column('publisher_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=240), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('domain', sa.Enum('Technology', 'Healthcare', 'Education', 'Environment', 'Finance', 'Agriculture', 'Logistics', name='problem_domain', native_enum=False, create_constraint=True), server_default='Technology', nullable=False),
    sa.Column('source', sa.Enum('industry', 'community', name='problem_source', native_enum=False, create_constraint=True), server_default='industry', nullable=False),
    sa.Column('csr', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'closed', 'archived', name='problem_status', native_enum=False, create_constraint=True), server_default='draft', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status = 'draft' OR (length(trim(title)) >= 3 AND length(trim(description)) >= 10 AND published_at IS NOT NULL)", name=op.f('ck_problems_published_brief')),
    sa.ForeignKeyConstraint(['publisher_id'], ['users.id'], name=op.f('fk_problems_publisher_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problems'))
    )
    op.create_index(op.f('ix_problems_csr'), 'problems', ['csr'], unique=False)
    op.create_index(op.f('ix_problems_domain'), 'problems', ['domain'], unique=False)
    op.create_index(op.f('ix_problems_publisher_id'), 'problems', ['publisher_id'], unique=False)
    op.create_index(op.f('ix_problems_status'), 'problems', ['status'], unique=False)
    op.create_table('teams',
    sa.Column('name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('leader_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('formed_by', sa.Enum('student', 'faculty', name='team_formed_by', native_enum=False, create_constraint=True), server_default='student', nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('forming', 'active', 'archived', name='team_status', native_enum=False, create_constraint=True), server_default='forming', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("formed_by <> 'faculty' OR institution_id IS NOT NULL", name=op.f('ck_teams_faculty_institution')),
    sa.CheckConstraint("formed_by <> 'student' OR leader_id = created_by_id", name=op.f('ck_teams_student_creator_leader')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_teams_team_name')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_teams_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_teams_institution_id_institutions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], name=op.f('fk_teams_leader_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_index(op.f('ix_teams_created_by_id'), 'teams', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_teams_institution_id'), 'teams', ['institution_id'], unique=False)
    op.create_index(op.f('ix_teams_leader_id'), 'teams', ['leader_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_digest', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), server_default='', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expires_at IS NOT NULL AND expires_at > created_at', name=op.f('ck_user_sessions_expiry_required')),
    sa.CheckConstraint('token_digest IS NOT NULL AND length(token_digest) >= 64', name=op.f('ck_user_sessions_digest_required')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_digest')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('faculty_problem_shortlists',
    sa.Column('faculty_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shortlisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_faculty_problem_shortlists_faculty_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_faculty_problem_shortlists_problem_id_problems'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faculty_problem_shortlists')),
    sa.UniqueConstraint('faculty_id', 'problem_id', name=op.f('uq_faculty_problem_shortlists_faculty_id'))
    )
    op.create_index(op.f('ix_faculty_problem_shortlists_faculty_id'), 'faculty_problem_shortlists', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_faculty_problem_shortlists_problem_id'), 'faculty_problem_shortlists', ['problem_id'], unique=False)
    op.create_table('problem_tags',
    sa.Column('problem_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=80), server_default='', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(label)) > 0 AND label = lower(trim(label))', name=op.f('ck_problem_tags_normalized_label')),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_problem_tags_problem_id_problems'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem_tags')),
    sa.UniqueConstraint('problem_id', 'label', name=op.f('uq_problem_tags_problem_id'))
    )
    op.create_index(op.f('ix_problem_tags_problem_id'), 'problem_tags', ['problem_id'], unique=False)
    op.create_table('projects',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('problem_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=240), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('category', sa.String(length=100), server_default='Technology', nullable=False),
    sa.Column('stage', sa.Enum('Ideation', 'Building', 'Prototype', 'Completed', name='project_stage', native_enum=False, create_constraint=True), server_default='Ideation', nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', name='project_status', native_enum=False, create_constraint=True), server_default='active', nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('repository_url', sa.Text(), nullable=True),
    sa.Column('demo_url', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(title)) >= 3 AND length(trim(description)) >= 10', name=op.f('ck_projects_project_brief')),
    sa.CheckConstraint('progress BETWEEN 0 AND 100', name=op.f('ck_projects_progress_range')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_projects_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_projects_institution_id_institutions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('fk_projects_problem_id_problems'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_projects_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_category'), 'projects', ['category'], unique=False)
    op.create_index(op.f('ix_projects_created_by_id'), 'projects', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_projects_institution_id'), 'projects', ['institution_id'], unique=False)
    op.create_index(op.f('ix_projects_problem_id'), 'projects', ['problem_id'], unique=False)
    op.create_index(op.f('ix_projects_stage'), 'projects', ['stage'], unique=False)
    op.create_index(op.f('ix_projects_team_id'), 'projects', ['team_id'], unique=False)
    op.create_table('team_memberships',
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('Invited', 'Member', 'Declined', 'Left', 'Removed', name='membership_status', native_enum=False, create_constraint=True), server_default='Invited', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'Member' OR (joined_at IS NOT NULL AND ended_at IS NULL)", name=op.f('ck_team_memberships_member_dates')),
    sa.CheckConstraint('ended_at IS NULL OR joined_at IS NULL OR ended_at >= joined_at', name=op.f('ck_team_memberships_membership_chronology')),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], name=op.f('fk_team_memberships_invited_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_memberships_team_id_teams'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_memberships_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_memberships')),
    sa.UniqueConstraint('team_id', 'user_id', name=op.f('uq_team_memberships_team_id'))
    )
    op.create_index(op.f('ix_team_memberships_invited_by_id'), 'team_memberships', ['invited_by_id'], unique=False)
    op.create_index(op.f('ix_team_memberships_status'), 'team_memberships', ['status'], unique=False)
    op.create_index(op.f('ix_team_memberships_team_id'), 'team_memberships', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_memberships_user_id'), 'team_memberships', ['user_id'], unique=False)
    op.create_table('collaboration_requests',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('member', 'mentor', name='collaboration_kind', native_enum=False, create_constraint=True), server_default='member', nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='collaboration_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_note', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'pending' AND responded_at IS NULL) OR (status <> 'pending' AND responded_at IS NOT NULL AND responded_at >= created_at)", name=op.f('ck_collaboration_requests_response_state')),
    sa.CheckConstraint('length(trim(reason)) >= 10', name=op.f('ck_collaboration_requests_reason_length')),
    sa.CheckConstraint('sender_id <> recipient_id', name=op.f('ck_collaboration_requests_different_parties')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_collaboration_requests_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_collaboration_requests_recipient_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_collaboration_requests_sender_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collaboration_requests'))
    )
    op.create_index('ix_collaboration_inbox', 'collaboration_requests', ['recipient_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_collaboration_requests_project_id'), 'collaboration_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_collaboration_requests_recipient_id'), 'collaboration_requests', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_collaboration_requests_sender_id'), 'collaboration_requests', ['sender_id'], unique=False)
    op.create_index('uq_collaboration_pending', 'collaboration_requests', ['project_id', 'recipient_id', 'kind'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('funding_records',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('leader_id', sa.Uuid(), nullable=False),
    sa.Column('funder_id', sa.Uuid(), nullable=False),
    sa.Column('responded_by_id', sa.Uuid(), nullable=True),
    sa.Column('amount_lakh', sa.Numeric(precision=16, scale=6), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('txn_ref', sa.String(length=240), server_default='', nullable=False),
    sa.Column('proof_file_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('proof_url', sa.Text(), nullable=True),
    sa.Column('proof_storage_key', sa.Text(), nullable=True),
    sa.Column('proof_mime_type', sa.String(length=127), nullable=True),
    sa.Column('proof_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('transfer_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('receipt_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.Enum('awaiting_leader', 'confirmed', 'declined', name='funding_status', native_enum=False, create_constraint=True), server_default='awaiting_leader', nullable=False),
    sa.Column('decline_note', sa.Text(), server_default='', nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('unverified', 'verified', 'rejected', name='funding_verification', native_enum=False, create_constraint=True), server_default='unverified', nullable=False),
    sa.Column('verified_by_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_note', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'awaiting_leader' AND responded_at IS NULL AND responded_by_id IS NULL AND NOT receipt_confirmed AND decline_note = '') OR (status = 'confirmed' AND responded_at IS NOT NULL AND responded_by_id IS NOT NULL AND responded_by_id = leader_id AND receipt_confirmed AND decline_note = '') OR (status = 'declined' AND responded_at IS NOT NULL AND responded_by_id IS NOT NULL AND responded_by_id = leader_id AND NOT receipt_confirmed AND length(trim(decline_note)) >= 5)", name=op.f('ck_funding_records_funding_decision')),
    sa.CheckConstraint("(verification_status = 'unverified' AND verified_at IS NULL AND verified_by_id IS NULL) OR (verification_status <> 'unverified' AND verified_at IS NOT NULL AND verified_by_id IS NOT NULL)", name=op.f('ck_funding_records_verification_state')),
    sa.CheckConstraint("amount_lakh > 0 AND currency = 'INR'", name=op.f('ck_funding_records_funding_amount')),
    sa.CheckConstraint('length(trim(txn_ref)) > 0 AND transfer_confirmed', name=op.f('ck_funding_records_transfer_proof')),
    sa.CheckConstraint('proof_size_bytes IS NULL OR proof_size_bytes >= 0', name=op.f('ck_funding_records_proof_size')),
    sa.CheckConstraint('responded_at IS NULL OR responded_at >= created_at', name=op.f('ck_funding_records_funding_dates')),
    sa.ForeignKeyConstraint(['funder_id'], ['users.id'], name=op.f('fk_funding_records_funder_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], name=op.f('fk_funding_records_leader_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_funding_records_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responded_by_id'], ['users.id'], name=op.f('fk_funding_records_responded_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], name=op.f('fk_funding_records_verified_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funding_records'))
    )
    op.create_index('ix_funding_latest', 'funding_records', ['project_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_funding_leader_pending', 'funding_records', ['leader_id', 'status'], unique=False)
    op.create_index(op.f('ix_funding_records_funder_id'), 'funding_records', ['funder_id'], unique=False)
    op.create_index(op.f('ix_funding_records_leader_id'), 'funding_records', ['leader_id'], unique=False)
    op.create_index(op.f('ix_funding_records_project_id'), 'funding_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_funding_records_responded_by_id'), 'funding_records', ['responded_by_id'], unique=False)
    op.create_index(op.f('ix_funding_records_verified_by_id'), 'funding_records', ['verified_by_id'], unique=False)
    op.create_table('milestones',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=240), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'submitted', 'changes_requested', 'approved', name='milestone_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'approved' AND approved_by_id IS NOT NULL AND approved_at IS NOT NULL) OR (status <> 'approved' AND approved_by_id IS NULL AND approved_at IS NULL)", name=op.f('ck_milestones_milestone_approval')),
    sa.CheckConstraint('length(trim(title)) > 0 AND position >= 0', name=op.f('ck_milestones_milestone_fields')),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_milestones_approved_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_milestones_created_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_milestones_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones'))
    )
    op.create_index(op.f('ix_milestones_approved_by_id'), 'milestones', ['approved_by_id'], unique=False)
    op.create_index(op.f('ix_milestones_created_by_id'), 'milestones', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_milestones_project_id'), 'milestones', ['project_id'], unique=False)
    op.create_table('project_activities',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=80), server_default='note', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_project_activities_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_activities_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_activities'))
    )
    op.create_index('ix_activity_project_created', 'project_activities', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_project_activities_actor_id'), 'project_activities', ['actor_id'], unique=False)
    op.create_index(op.f('ix_project_activities_project_id'), 'project_activities', ['project_id'], unique=False)
    op.create_table('proof_entries',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=240), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(title)) >= 3', name=op.f('ck_proof_entries_proof_title')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_proof_entries_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_proof_entries_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proof_entries'))
    )
    op.create_index(op.f('ix_proof_entries_author_id'), 'proof_entries', ['author_id'], unique=False)
    op.create_index(op.f('ix_proof_entries_project_id'), 'proof_entries', ['project_id'], unique=False)
    op.create_index('ix_proof_project_created', 'proof_entries', ['project_id', 'created_at'], unique=False)
    op.create_table('reviews',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('strengths', sa.Text(), server_default='', nullable=False),
    sa.Column('flaws', sa.Text(), server_default='', nullable=False),
    sa.Column('improvements', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.Enum('open', 'addressed', 'resolved', name='review_status', native_enum=False, create_constraint=True), server_default='open', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'resolved' AND resolved_at IS NOT NULL AND resolved_by_id = reviewer_id) OR (status <> 'resolved' AND resolved_at IS NULL AND resolved_by_id IS NULL)", name=op.f('ck_reviews_resolution_state')),
    sa.CheckConstraint('length(trim(summary)) >= 10 AND length(trim(flaws)) >= 10 AND length(trim(improvements)) >= 10', name=op.f('ck_reviews_review_lengths')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_reviews_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_reviews_resolved_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_index('ix_review_project_status', 'reviews', ['project_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_reviews_project_id'), 'reviews', ['project_id'], unique=False)
    op.create_index(op.f('ix_reviews_resolved_by_id'), 'reviews', ['resolved_by_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.create_table('mentor_assignments',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('mentor_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_mentor_assignments_assignment_dates')),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_mentor_assignments_assigned_by_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], name=op.f('fk_mentor_assignments_mentor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_mentor_assignments_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['collaboration_requests.id'], name=op.f('fk_mentor_assignments_request_id_collaboration_requests'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentor_assignments')),
    sa.UniqueConstraint('request_id', name=op.f('uq_mentor_assignments_request_id'))
    )
    op.create_index(op.f('ix_mentor_assignments_assigned_by_id'), 'mentor_assignments', ['assigned_by_id'], unique=False)
    op.create_index(op.f('ix_mentor_assignments_mentor_id'), 'mentor_assignments', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_mentor_assignments_project_id'), 'mentor_assignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_mentor_assignments_request_id'), 'mentor_assignments', ['request_id'], unique=False)
    op.create_index('uq_mentor_current_project', 'mentor_assignments', ['project_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    op.create_table('notifications',
    sa.Column('recipient_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('collaboration_request_id', sa.Uuid(), nullable=True),
    sa.Column('funding_record_id', sa.Uuid(), nullable=True),
    sa.Column('review_id', sa.Uuid(), nullable=True),
    sa.Column('change_request_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('collaboration', 'funding', 'review', 'institution_change', 'milestone', 'system', name='notification_kind', native_enum=False, create_constraint=True), server_default='system', nullable=False),
    sa.Column('title', sa.String(length=240), server_default='', nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deduplication_key', sa.String(length=240), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(title)) > 0', name=op.f('ck_notifications_notification_title')),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_notifications_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['change_request_id'], ['institution_change_requests.id'], name=op.f('fk_notifications_change_request_id_institution_change_requests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['collaboration_request_id'], ['collaboration_requests.id'], name=op.f('fk_notifications_collaboration_request_id_collaboration_requests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['funding_record_id'], ['funding_records.id'], name=op.f('fk_notifications_funding_record_id_funding_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_notifications_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_notifications_review_id_reviews'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('recipient_id', 'deduplication_key', name=op.f('uq_notifications_recipient_id'))
    )
    op.create_index('ix_notification_unread', 'notifications', ['recipient_id', 'created_at'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_index(op.f('ix_notifications_actor_id'), 'notifications', ['actor_id'], unique=False)
    op.create_index(op.f('ix_notifications_change_request_id'), 'notifications', ['change_request_id'], unique=False)
    op.create_index(op.f('ix_notifications_collaboration_request_id'), 'notifications', ['collaboration_request_id'], unique=False)
    op.create_index(op.f('ix_notifications_funding_record_id'), 'notifications', ['funding_record_id'], unique=False)
    op.create_index(op.f('ix_notifications_project_id'), 'notifications', ['project_id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_notifications_review_id'), 'notifications', ['review_id'], unique=False)
    op.create_table('proof_attachments',
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('image', 'link', 'video', name='attachment_kind', native_enum=False, create_constraint=True), server_default='link', nullable=False),
    sa.Column('source', sa.Enum('upload', 'external', name='attachment_source', native_enum=False, create_constraint=True), server_default='external', nullable=False),
    sa.Column('url', sa.Text(), server_default='', nullable=False),
    sa.Column('name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=127), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("checksum_sha256 IS NULL OR checksum_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_proof_attachments_checksum_format')),
    sa.CheckConstraint("source <> 'upload' OR (storage_key IS NOT NULL AND length(storage_key) > 0 AND mime_type IS NOT NULL AND size_bytes IS NOT NULL AND ((kind = 'image' AND mime_type LIKE 'image/%%' AND size_bytes <= 2097152) OR (kind = 'video' AND mime_type LIKE 'video/%%' AND size_bytes <= 104857600)))", name=op.f('ck_proof_attachments_upload_limits')),
    sa.CheckConstraint("url ~ '^https?://[^[:space:]/]+[^[:space:]]*$' OR (source = 'upload' AND url LIKE '/_upload/%%')", name=op.f('ck_proof_attachments_attachment_url')),
    sa.CheckConstraint('position >= 0 AND (size_bytes IS NULL OR size_bytes >= 0)', name=op.f('ck_proof_attachments_attachment_numbers')),
    sa.ForeignKeyConstraint(['entry_id'], ['proof_entries.id'], name=op.f('fk_proof_attachments_entry_id_proof_entries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proof_attachments')),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_proof_attachments_entry_id'), 'proof_attachments', ['entry_id'], unique=False)
    op.create_table('review_panel_feedback',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.Column('faculty_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('decision', sa.Enum('feedback', 'changes_requested', 'approved', name='panel_decision', native_enum=False, create_constraint=True), server_default='feedback', nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(body)) > 0', name=op.f('ck_review_panel_feedback_panel_feedback_required')),
    sa.CheckConstraint('score IS NULL OR score BETWEEN 0 AND 100', name=op.f('ck_review_panel_feedback_panel_score')),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_review_panel_feedback_faculty_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], name=op.f('fk_review_panel_feedback_milestone_id_milestones'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_review_panel_feedback_project_id_projects'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_panel_feedback'))
    )
    op.create_index(op.f('ix_review_panel_feedback_faculty_id'), 'review_panel_feedback', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_review_panel_feedback_milestone_id'), 'review_panel_feedback', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_review_panel_feedback_project_id'), 'review_panel_feedback', ['project_id'], unique=False)
    op.create_table('review_replies',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('author_role', sa.Enum('student', 'industry', name='reply_author_role', native_enum=False, create_constraint=True), server_default='student', nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('action', sa.Enum('comment', 'changes_done', 'request_changes', 'resolve', name='reply_action', native_enum=False, create_constraint=True), server_default='comment', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action = 'comment' OR (action = 'changes_done' AND author_role = 'student') OR (action IN ('request_changes', 'resolve') AND author_role = 'industry')", name=op.f('ck_review_replies_reply_action_role')),
    sa.CheckConstraint('length(trim(body)) > 0', name=op.f('ck_review_replies_reply_required')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_review_replies_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_replies_review_id_reviews'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_replies'))
    )
    op.create_index(op.f('ix_review_replies_author_id'), 'review_replies', ['author_id'], unique=False)
    op.create_index(op.f('ix_review_replies_review_id'), 'review_replies', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_replies_review_id'), table_name='review_replies')
    op.drop_index(op.f('ix_review_replies_author_id'), table_name='review_replies')
    op.drop_table('review_replies')
    op.drop_index(op.f('ix_review_panel_feedback_project_id'), table_name='review_panel_feedback')
    op.drop_index(op.f('ix_review_panel_feedback_milestone_id'), table_name='review_panel_feedback')
    op.drop_index(op.f('ix_review_panel_feedback_faculty_id'), table_name='review_panel_feedback')
    op.drop_table('review_panel_feedback')
    op.drop_index(op.f('ix_proof_attachments_entry_id'), table_name='proof_attachments')
    op.drop_table('proof_attachments')
    op.drop_index(op.f('ix_notifications_review_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_project_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_funding_record_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_collaboration_request_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_change_request_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_actor_id'), table_name='notifications')
    op.drop_index('ix_notification_unread', table_name='notifications', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_table('notifications')
    op.drop_index('uq_mentor_current_project', table_name='mentor_assignments', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_index(op.f('ix_mentor_assignments_request_id'), table_name='mentor_assignments')
    op.drop_index(op.f('ix_mentor_assignments_project_id'), table_name='mentor_assignments')
    op.drop_index(op.f('ix_mentor_assignments_mentor_id'), table_name='mentor_assignments')
    op.drop_index(op.f('ix_mentor_assignments_assigned_by_id'), table_name='mentor_assignments')
    op.drop_table('mentor_assignments')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_resolved_by_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_project_id'), table_name='reviews')
    op.drop_index('ix_review_project_status', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_proof_project_created', table_name='proof_entries')
    op.drop_index(op.f('ix_proof_entries_project_id'), table_name='proof_entries')
    op.drop_index(op.f('ix_proof_entries_author_id'), table_name='proof_entries')
    op.drop_table('proof_entries')
    op.drop_index(op.f('ix_project_activities_project_id'), table_name='project_activities')
    op.drop_index(op.f('ix_project_activities_actor_id'), table_name='project_activities')
    op.drop_index('ix_activity_project_created', table_name='project_activities')
    op.drop_table('project_activities')
    op.drop_index(op.f('ix_milestones_project_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_created_by_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_approved_by_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_funding_records_verified_by_id'), table_name='funding_records')
    op.drop_index(op.f('ix_funding_records_responded_by_id'), table_name='funding_records')
    op.drop_index(op.f('ix_funding_records_project_id'), table_name='funding_records')
    op.drop_index(op.f('ix_funding_records_leader_id'), table_name='funding_records')
    op.drop_index(op.f('ix_funding_records_funder_id'), table_name='funding_records')
    op.drop_index('ix_funding_leader_pending', table_name='funding_records')
    op.drop_index('ix_funding_latest', table_name='funding_records')
    op.drop_table('funding_records')
    op.drop_index('uq_collaboration_pending', table_name='collaboration_requests', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_collaboration_requests_sender_id'), table_name='collaboration_requests')
    op.drop_index(op.f('ix_collaboration_requests_recipient_id'), table_name='collaboration_requests')
    op.drop_index(op.f('ix_collaboration_requests_project_id'), table_name='collaboration_requests')
    op.drop_index('ix_collaboration_inbox', table_name='collaboration_requests')
    op.drop_table('collaboration_requests')
    op.drop_index(op.f('ix_team_memberships_user_id'), table_name='team_memberships')
    op.drop_index(op.f('ix_team_memberships_team_id'), table_name='team_memberships')
    op.drop_index(op.f('ix_team_memberships_status'), table_name='team_memberships')
    op.drop_index(op.f('ix_team_memberships_invited_by_id'), table_name='team_memberships')
    op.drop_table('team_memberships')
    op.drop_index(op.f('ix_projects_team_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_stage'), table_name='projects')
    op.drop_index(op.f('ix_projects_problem_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_institution_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_by_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_category'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_problem_tags_problem_id'), table_name='problem_tags')
    op.drop_table('problem_tags')
    op.drop_index(op.f('ix_faculty_problem_shortlists_problem_id'), table_name='faculty_problem_shortlists')
    op.drop_index(op.f('ix_faculty_problem_shortlists_faculty_id'), table_name='faculty_problem_shortlists')
    op.drop_table('faculty_problem_shortlists')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_teams_leader_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_institution_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_created_by_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_problems_status'), table_name='problems')
    op.drop_index(op.f('ix_problems_publisher_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_domain'), table_name='problems')
    op.drop_index(op.f('ix_problems_csr'), table_name='problems')
    op.drop_table('problems')
    op.drop_index('uq_portfolio_current_owner', table_name='portfolio_shares', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_portfolio_shares_owner_id'), table_name='portfolio_shares')
    op.drop_table('portfolio_shares')
    op.drop_index('uq_student_pending_change', table_name='institution_change_requests', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index(op.f('ix_institution_change_requests_to_institution_id'), table_name='institution_change_requests')
    op.drop_index(op.f('ix_institution_change_requests_student_id'), table_name='institution_change_requests')
    op.drop_index(op.f('ix_institution_change_requests_responded_by_id'), table_name='institution_change_requests')
    op.drop_index(op.f('ix_institution_change_requests_from_institution_id'), table_name='institution_change_requests')
    op.drop_index(op.f('ix_institution_change_requests_faculty_id'), table_name='institution_change_requests')
    op.drop_table('institution_change_requests')
    op.drop_index('uq_users_email_normalized', table_name='users')
    op.drop_index(op.f('ix_users_registered_by_id'), table_name='users')
    op.drop_index(op.f('ix_users_institution_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_institutions_name', table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
