"""add_api_audits

Revision ID: 5d60f9b39482
Revises: 4731ae582abc
Create Date: 2026-09-21 16:25:27.318440
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5d60f9b39482'
down_revision: Union[str, Sequence[str], None] = '4731ae582abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_audits',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), server_default='', nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('subject_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_api_audits_actor_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_audits'))
    )
    op.create_index('ix_api_audit_subject_time', 'api_audits', ['subject_hash', 'created_at'], unique=False)
    op.create_index(op.f('ix_api_audits_action'), 'api_audits', ['action'], unique=False)
    op.create_index(op.f('ix_api_audits_actor_id'), 'api_audits', ['actor_id'], unique=False)
    op.create_index(op.f('ix_api_audits_subject_hash'), 'api_audits', ['subject_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_audits_subject_hash'), table_name='api_audits')
    op.drop_index(op.f('ix_api_audits_actor_id'), table_name='api_audits')
    op.drop_index(op.f('ix_api_audits_action'), table_name='api_audits')
    op.drop_index('ix_api_audit_subject_time', table_name='api_audits')
    op.drop_table('api_audits')
    # ### end Alembic commands ###
