import { useEffect, useRef, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { all, resource, type Page } from './api';
import type { Project, Proof } from './records';
import { panel, button } from './auth';
interface Portfolio { profile: { display_name: string; bio: string; institution: string; linkedin_url: string | null }; projects: Page<Project> }
export default function SharedPortfolio() {
  const { slug = '' } = useParams(); const [value, setValue] = useState<Portfolio | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [proofs, setProofs] = useState<Record<string, Proof[]>>({});
  const generation = useRef(0);
  async function load() { const ticket = ++generation.current; setBusy(true); setError(''); try { const next = await resource<Portfolio>(`/public/portfolios/${encodeURIComponent(slug)}`); if (ticket === generation.current) { setValue(next); setProofs({}); } } catch (e) { if (ticket === generation.current) { setValue(null); setProofs({}); setError(e instanceof Error ? e.message : 'Portfolio unavailable'); } } finally { if (ticket === generation.current) setBusy(false); } }
  useEffect(() => { setValue(null); setProofs({}); void load(); const resume = () => { if (!document.hidden) void load(); }; window.addEventListener('focus', resume); document.addEventListener('visibilitychange', resume); return () => { generation.current++; window.removeEventListener('focus', resume); document.removeEventListener('visibilitychange', resume); }; }, [slug]);
  async function more() { if (!value) return; const ticket = generation.current; setBusy(true); try { const next = await resource<Portfolio>(`/public/portfolios/${encodeURIComponent(slug)}?offset=${value.projects.items.length}`); if (ticket === generation.current) setValue({ ...next, projects: { ...next.projects, items: [...value.projects.items, ...next.projects.items] } }); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load'); } finally { setBusy(false); } }
  async function evidence(id: string) { const ticket = generation.current; setError(''); try { const items = await all<Proof>(`/public/portfolios/${encodeURIComponent(slug)}/projects/${id}/proofs`); if (ticket === generation.current) setProofs(p => ({ ...p, [id]: items })); } catch (e) { if (ticket === generation.current) { setProofs({}); setValue(null); setError(e instanceof Error ? e.message : 'Evidence unavailable'); } } }
  return <main className="min-h-screen bg-[var(--background)] text-[var(--foreground)] font-['DM_Sans'] p-6 md:p-10"><div className="max-w-6xl mx-auto"><Link to="/" className="text-sm text-indigo-300">InnovateX · Public portfolio</Link>{busy && <p role="status" className="text-sm my-5">Loading portfolio…</p>}{error && <div className={`${panel} mt-5`}><p role="alert">{error}</p><button className={button} onClick={() => void load()}>Retry</button></div>}{value && <><header className="py-8"><h1 className="text-3xl font-bold">{value.profile.display_name}</h1><p className="text-sm text-[var(--muted-foreground)] mt-2">{value.profile.institution}</p><p className="text-sm mt-4">{value.profile.bio}</p>{value.profile.linkedin_url && <a href={value.profile.linkedin_url} target="_blank" rel="noopener noreferrer" className="text-xs text-indigo-300">LinkedIn ↗</a>}</header><div className="grid md:grid-cols-2 gap-5">{value.projects.items.map(p => <article className={panel} key={p.id}><span className="text-xs text-indigo-300">{p.display_stage || p.stage} · {p.progress}%</span><h2 className="font-semibold text-lg mt-2">{p.title}</h2><p className="text-sm text-[var(--muted-foreground)] my-3">{p.description}</p><progress className="accent-indigo-500 w-full h-1.5" max={100} value={p.progress} /><button className="block text-xs text-indigo-300 mt-4" onClick={() => void evidence(p.id)}>View proof of work</button>{proofs[p.id]?.map(proof => <div className="mt-4 border-t border-[var(--border)] pt-3" key={proof.id}><h3 className="text-sm font-semibold">{proof.title}</h3><p className="text-xs text-[var(--muted-foreground)] mt-2">{proof.description}</p><p className="text-xs text-[var(--muted-foreground)] mt-2">{new Date(proof.created_at).toLocaleString()}</p>{proof.attachments.map((a, i) => <a key={i} href={a.url} target="_blank" rel="noopener noreferrer" className="block text-xs text-indigo-300 mt-2">{a.name || a.kind} ↗</a>)}</div>)}{proofs[p.id]?.length === 0 && <p className="text-xs mt-3">No proof published yet.</p>}</article>)}</div>{!value.projects.items.length && <p className={panel}>No public projects yet.</p>}{value.projects.items.length < value.projects.total && <button className={`${button} mt-5`} disabled={busy} onClick={() => void more()}>Load more projects</button>}</>}</div></main>;
}
